Add files via upload

diff --git a/retroports b/retroports
--- a/retroports
+++ b/retroports
@@ -71,7 +71,7 @@ fi
 # SYNC AND UPDATE
 UPDATE() {
   printf '%s\n' "Wait...Wait... Starting UPDATE in ${dir_ports}/${VERSION}."
-  if ! rsync -avzh "rsync://slackbuilds.org/slackbuilds/${VERSION} ${dir_ports}"; then
+  if ! rsync -avzh "rsync://slackbuilds.org/slackbuilds/${VERSION}" "${dir_ports}"; then
       printf '%s\n' "ErrooooooooOOOOOr."
       exit 1
   else
@@ -122,6 +122,26 @@ SEARCH() {
  fi
 }
 
+DOWNLOAD_SRC() {
+    packInfo="$(find . -name *.info)"
+    if [ -n "${packInfo}" ] && [ -e "$packInfo" ]; then
+        . ${packInfo} # Load lib
+        printf '%s' "Start download of ${PRGNAM} ${VERSION}? [y/N] "
+        read -r inputUser
+        # Input Lower.
+        inputUser=$(printf '%s' "$inputUser" | tr [:upper:] [:lower:])
+        [ -z "$inputUser"  ] && inputUser='N'
+        if [ "$inputUser" = 'y' ]; then
+            printf '%s\n' "Start Download AT: ${DOWNLOAD}"
+            if wget --progress=bar "${DOWNLOAD}"; then
+                printf '%s\n' "Check MD5SUM..."
+                take_md5_file="$(md5sum ${PRGNAM}-${VERSION}* | cut -d ' ' -f 1)"
+                [ "$take_md5_file" = "$MD5SUM" ] && printf '%s\n' "MD5 OK." || printf '%s\n' "MD5 ERROR."
+            fi
+        fi
+    fi
+}
+
 #====================== TESTS
 [ "$(id -u)" -ne '0' ] && { echo "Need root ;)."; exit 1 ;}
 
@@ -137,6 +157,8 @@ elif [ "$1" = '--search' ] || [ "$1" = 'search' ]; then
     else
         USAGE
     fi
+elif [ "$1" = '--download' ] || [ "$1" = 'download' ]; then
+    DOWNLOAD_SRC
 else
     USAGE
 fi
